### PR TITLE
Use GitHub actions

### PR DESCRIPTION
**Pull request by ericpre**
As mentioned in https://github.com/LumiSpy/lumispy/pull/43#issuecomment-737243218, travis CI is not reliable anymore.
- [x] Move test suite run from travis to github actions
- [x] tidy up unnecessary files and dependencies
- [x] update badge.

### CODE REVIEW

**Comment by ericpre** [comment]
To enable the github actions in this repository, one branch needs to have a workflow - see for example: https://github.com/ericpre/lumispy/actions

**Comment by ericpre** [comment]
https://coveralls.io/builds/35394013

**Comment by jlaehne** [comment]
Thanks, that was quick!

**Comment by jordiferrero** [comment]
A huge thanks to @ericpre! That was very quick feedback.
So I understand better, do I need to create an action for the lumispy/Lumispy master branch?

**Comment by ericpre** [comment]
> * When we test, should we also have a testing environment in which the `non-linear-axis` hyperspy version is **not** installed? That's for completeness.

Indeed, it may be good to do this and adjust the test suite accordingly - I guess I use this branch of hyperspy because the test suite was failing.

**Comment by jlaehne** [comment]
OK, I will adapt the tests in #43 and #46 to distinguish between non-uniform-axes and the main hyperspy branch for the moment.

**Pull request merged**
