### PR TITLE
Improve coverage

### PR DESCRIPTION
**Pull request by jordiferrero**
### Description of the change
Add tests for `px_to_nm_grating_solver` 

### Progress of the PR
- [x] added tests,
- [x] check coverage and correct until perfect
- [x] ready for review.

### CODE REVIEW

**Comment by jordiferrero** [comment]
@jlaehne Can't seem to see why coverage is not 100%... which lines/files are causing it?

**Comment by jlaehne** [comment]
It was three lines in `remove_background_from_file` (exceptions and warnings). I added a commit to ignore them as we want to deprecate that function anyway.

**Comment by jlaehne** [comment]
100%: https://app.codecov.io/github/LumiSpy/lumispy/pull/145

**Review by jlaehne — APPROVED** [review]

**Comment by jordiferrero** [comment]
Thanks. Silly question... but how did you commit to my personal branch whist doing a PR?

**Comment by jlaehne** [comment]
Good question, it just offered me to open a PR or commit directly and even though I expected it not to work I tried the direct commit.

**Pull request merged**
