### PR TITLE
Release_v0.2.2

### PR DESCRIPTION
**Pull request by jlaehne**
### Description of the change
I'd like to push a patch release before the tutorial at the CL-EBIC workshop next week.

### Progress of the PR
- [x] bumped version,
- [X] updated CHANGELOG.md,
- [X] ready for review.

### CODE REVIEW

**Comment by ericpre** [comment]
> I'd like to push a patch release before the tutorial at the CL-EBIC workshop next week.

Do you think that we should release a hyperspy patch release asap to avoid potential troubles with the random number generation changes in recent version of dask?

**Comment by jlaehne** [comment]
> > I'd like to push a patch release before the tutorial at the CL-EBIC workshop next week.
> 
> Do you think that we should release a hyperspy patch release asap to avoid potential troubles with the random number generation changes in recent version of dask?

Haven't looked into the details, but sounds sensible and might not hurt.

**Comment by jlaehne** [comment]
I just realized that for a map the new `centroid` function, similar to e.g. `valuemax` and `indexmax` in HyperSpy returns a BaseSignal with 2 navigation dimensions and 0D signal, which theoretically makes sense, but is inconvenient for plotting as it plots including the navigator, which makes little sense for 0D signals, and colormap cannot be changed.

In contrast, `estimate_peak_width` returns the transposed signal, thus Signal2D object without navigation dimensions, which is more convenient for plotting - and is okay in the sense that it is just an image of values for the different positions.

We should consider making that more consistent also in HyperSpy (e.g. with the 2.0 release), but if we release the `centroid` function here and then decide to change the behavior again, we unnecessarily break the API.

**Comment by jlaehne** [comment]
I changed the `centroid` output type to `Signal2D`  in #184 and opened an issue for HyperSpy https://github.com/hyperspy/hyperspy/issues/3111

**Pull request merged**
