### PR TITLE
Migrate to pyproject.toml, activate towncrier, update release workflow

### PR DESCRIPTION
**Pull request by jlaehne**
### Description of the change
- Migrate to `pyproject.toml` to replace `setup.py` (see e.g. https://github.com/hyperspy/holospy/pull/14)
- Activate towncrier for changelog (see e.g. https://github.com/hyperspy/holospy/pull/17)
- Update release workflow to match the one of HyperSpy and other extensions. Related todo:

  - [x] Set up trusted publisher on PyPI.
  - [ ] Disable PyPI token if new workflow works correctly.
  - [ ] Do we need to change anything on the zenodo setup?

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] docstring updated (if appropriate),
- [x] update user guide (if appropriate),
- [n/a] added tests,
- [x] added changelog entries to ``upcoming_changes``,
- [x] test formatting of changelog,
- [x] ready for review.

### CODE REVIEW

**Comment by jlaehne** [comment]
@ericpre is there a way to make the hyperspy `package_and_test` workflow available for lumispy or should I work on simplifying the copy made here instead? As far as I can see, in particular [`l65](https://github.com/hyperspy/.github/blob/e9fc394a77d4f8df3518b59c3dfb6ba51aa19874/.github/workflows/package_and_test.yml#L65) is incompatible with being called from outside the hyperspy organization.

**Comment by ericpre** [comment]
Can you try now after https://github.com/hyperspy/.github/commit/c5376fc1205d57561ac5e15620df4e5799465a5c?

**Comment by jlaehne** [comment]
> Can you try now after [hyperspy/.github@c5376fc](https://github.com/hyperspy/.github/commit/c5376fc1205d57561ac5e15620df4e5799465a5c)?

Still trying to run `git remote add upstream https://github.com/hyperspy/lumispy.git`:
https://github.com/LumiSpy/lumispy/actions/runs/8944482220/job/24571487005?pr=211

**Review by ericpre — COMMENTED** [review]
That looks all good and working as expected.

I think that it should be possible to remove the [`MANIFEST.in`](https://github.com/LumiSpy/lumispy/blob/main/MANIFEST.in) file.

>   - [ ] Do we need to change anything on the zenodo setup?

Not that I am aware of!


Is it worth updating the doc workflow? For example:

https://github.com/hyperspy/rosettasciio/blob/fa68311843db1e10d070d23c6691289c3b93ba32/.github/workflows/docs.yml#L1-L12

**Comment by jlaehne** [comment]
> Is it worth updating the doc workflow? For example:

I see that the `[push_doc.yml](https://github.com/hyperspy/.github/blob/main/.github/workflows/push_doc.yml)` workflow relies on tokens that can probably not be shared across organisations?

**Comment by ericpre** [comment]
Which tokens?

This is the workflow:
https://github.com/hyperspy/.github/blob/main/.github/workflows/doc.yml

**Review by ericpre — APPROVED** [review]

**Comment by jlaehne** [comment]
`doc.yml` uses `push_doc.yml`, which uses access tokens: https://github.com/hyperspy/.github/blob/c5376fc1205d57561ac5e15620df4e5799465a5c/.github/workflows/push_doc.yml#L83

I'll merge this PR and the doc workflow could become a new one.

**Pull request merged**
