### PR TITLE
Clean up namespace

### PR DESCRIPTION
**Pull request by jlaehne**
Based on the comment from at https://github.com/LumiSpy/lumispy/issues/17#issuecomment-767030637 I cleaned up the namespace in analogy to https://github.com/pyxem/pyxem/pull/704.

Progress:
- [X] Changes implemented
- [X] Adapted tests
- [x] Check again
- [x] Ready for review

Example:
Signals would be initiated as in HyperSpy and pyxem: 
 s = lum.signals.LumiSpectrum(np.arange(10))

### CODE REVIEW

**Comment by jlaehne** [comment]
I'm thinking of joining all the three CL related files in `signals` into `cl_spectrum.py`.  I do not think we need to have so many different files, what do you think @jordiferrero @dnjohnstone . I've seen that in pyxem quite a number of different (though related) signal types are in one file.

**Review by jordiferrero — APPROVED** [review]

**Review by jordiferrero — APPROVED** [review]

**Comment by jordiferrero** [comment]
> I'm thinking of joining all the three CL related files in `signals` into `cl_spectrum.py`. I do not think we need to have so many different files, what do you think @jordiferrero @dnjohnstone . I've seen that in pyxem quite a number of different (though related) signal types are in one file.

I am not sure about this...
When we discussed the initial signals structure, we realised that we needed some CL signals as some functions are only relevant for SEM and others are more general. I personally only work with SEM_CL data and like to have a special file with the functions for it (it's easier to navigate through classes).

I assume you are proposing to have the 3 classes in one file, right?
Happy to discuss further, but I would not merge them.

**Comment by jlaehne** [comment]
Yep, that is exactly what I was thinking. 3 classes in one file. So we would have files for EL, PL, CL, but subclasses would be in the same.

I don't think there will be so many functions that are specific only to SEM or TEM. So far I mostly still have my signals as CLSpectrum.

We could also merge them now and if it ever gets too crowded still separate them.

Just some ideas, I am not passionate about either solution.

**Comment by jordiferrero** [comment]
@jlaehne I agree to go ahead and merge the 3 classes in one file.
If you update this PR with those changes we can aprove it.

**Comment by jlaehne** [comment]
done

(I tried to introduce a test for a warning from #44, but that would require the github-actions to include a hyperspy-gui package, so it is commented out for the moment. We can add that in a later PR to improve coverage.)

**Pull request merged**
