### PR TITLE
New functions: remove_negative, normalize, scale_by_exposure

### PR DESCRIPTION
**Pull request by jlaehne**
### Description of the change
Add functions to
- set all negative data to a certain value
- normalize spectra
- scale spectra by exposure (for comparison of data with different exposure times)
  (Can be later improved to search for appropriate keywords in metadata using https://github.com/hyperspy/hyperspy/pull/2633)

### Progress of the PR
- [X] Change implemented (can be split into several points),
- [X] update docstring (if appropriate),
- [x] add tests,
- [x] ready for review.

### Minimal example of the bug fix or the new feature
```python
import lumispy as lum
import numpy as np
s = lum.signals.LumiSpectrum(np.random.random(10))
s.scale_by_exposure(exposure=0.5,inplace=True)
s.normalize(inplace=True)
```

### CODE REVIEW

**Comment by jordiferrero** [comment]
Sorry for the late review.
Very useful functions, especially the scaling by exposure.

With the recent updates, there are some small conflicts before we can merge.

As a side note, that reminds me that we need some way to standardise "luminescence specific" metadata so it can be read by the functions. I will open an issue now.

**Comment by jlaehne** [comment]
I'll fix the conflicts once #49 is merged (which likely introduces more conflicts).

**Comment by jordiferrero** [comment]
> I'll fix the conflicts once #49 is merged (which likely introduces more conflicts).

Done.

**Comment by jlaehne** [comment]
Ready :-)

**Pull request merged**
