### PR TITLE
Energy conversion of signal axis

### PR DESCRIPTION
**Pull request by jlaehne**
### Description of the change
As discussed in #14, I implemented and extended my function to convert the signal axis to energy. Includes wavelength dependent permittivity of air (minor correction for very precise data). Corrects intensities so that integrals are correct. Defaults to nm, but can handle µm if explicitly set.
Includes two helper functions `nm2eV` and `eV2nm` for back and forth calculation.

### Progress of the PR
- [X] Change implemented (can be split into several points),
- [X] Raise error when non_uniform_axes functionality is not available from hyperspy,
- [X] Convert to object oriented function,
- [X] Add inplace functionality
- [x] Signal type and metadata for inplace=False
- [X] update docstring (if appropriate),
- [x] add tests,
- [x] ready for review.

### CODE REVIEW

**Comment by jordiferrero** [comment]
Thanks @jlaehne for starting this implementation!
It looks good to me! 
I have some comments:
- Using the `.to_eV` function creates a new object with `Signal1D` class (not the luminescence specific classes)
- Using the `.to_eV` function will lose the metadata from the original signal?
Is there a way to get around this issues?

**Comment by jlaehne** [comment]
Good points. So far it is mainly the hack I was using personally.

I could try to also have the creation of the extra signal object optional and otherwise replace the existing object. As the data has to be inverted along the signal axis and the axis replaced, I refrained from messing in place so far. For large signals, it may though be attractive to not create a whole copy. What do you think?

**Comment by jordiferrero** [comment]
I personally prefer the modification of the existing signal by default, because of memory usage mainly and also you run away from problems of losing stored metadata, models... which is annoying.

Maybe you can include the `inplace` parameter (like in the `.map()` function which can trigger the creation of a new object if False.

**Comment by jlaehne** [comment]
Converted it to an object oriented function. For the `luminescence_spectrum` class, so there will need to be a slightly different implementation for time-resolved data, once we add that (because we will have two signal axes and have to convert the right one).
Inplace function should work now, for `inplace=False` I need to use the right Signal type and copy metadata.

**Comment by jlaehne** [comment]
Should all be implemented.

Coverage seems to have some trouble. I get 46% and not 0% locally. Also the Travis fail does not seem related to the new code.

**Comment by jordiferrero** [comment]
I'll have a look at the issues with Travis and coveralls... 
For now I will merge this PR as it is working well. Thank you!
It would be nice to have a demo for that in `lumispy-demos`. I will try to create that.

**Comment by jordiferrero** [comment]
@jlaehne I have also added a section in the installation guide explaining how to install the development hyperspy version of `non-uniform-axes`.

**Comment by jlaehne** [comment]
> It would be nice to have a demo for that in `lumispy-demos`. I will try to create that.
I could do that as well, just wanted to wait for the PR to be merged. Just let me know how you prefer.

I also started working on an equivalent function for wavenumber (to_invcm). For e.g. Raman community that is essential. Only, I do not have so much experience with Raman myself so that I might try to briefly discuss with a colleague before I put it forward.

**Pull request merged**
