### PR TITLE
implemented wavenumber conversion

### PR DESCRIPTION
**Pull request by jlaehne**
Extend the axis conversion utility to also handle wavenumbers (units of inverse cm) similar to the energy conversion from #37.

Includes two helper functions `nm2invcm` and `invcm2nm` for back and forth calculation.

### Progress of the PR
- [X] Change implemented in analogy to #37,
- [X] Raise error when non_uniform_axes functionality is not available from hyperspy,
- [x] Add function to calculate axis as relative wavenumber for given laser wavelength
- [X] update docstring (if appropriate),
- [x] add tests,
- [x] ready for review.

### CODE REVIEW

**Review by jordiferrero — COMMENTED** [review]
Thanks for these fundamental functions.
There are 2 things to discuss before merge:

- Do you think maybe renaming the `axis2invcm`, the `nm2invcm` .... functions to a clearer name would be beneficial for other contributors. What about something a bit more lengthy like `axis_to_inverse_cm`, `nm_to_inverse_cm` ...

- The coveralls check failed. (in case you don't know what it does, it basically checks it all the lines added in the PR are tested in the test files). The tests you have written are good (they pass) but a large part of your code is not tested. That may be because of the very basic functions you have added. 
For now I am happy to merge if you don't have time now to expand your tests. But ideally, (almost) every line of code you add should be tested (and for a robust package, we should aim at having >90% coverage).
You can check what lines/functions lack a test by clicking on the `coverage/coveralls` detail and seeing which lines of code are in red. 

Let me know what you think of these 2 changes :-)

**Comment by jlaehne** [comment]
>     * Do you think maybe renaming the `axis2invcm`, the `nm2invcm` .... functions to a clearer name would be beneficial for other contributors. What about something a bit more lengthy like `axis_to_inverse_cm`, `nm_to_inverse_cm` ...
> 
I used the same naming convention I used for `axis2eV` `nm2eV` and `eV2nm` and I wanted to avoid too lengthy names.

>     * The coveralls check failed. (in case you don't know what it does, it basically checks it all the lines added in the PR are tested in the test files). The tests you have written are good (they pass) but a large part of your code is not tested. That may be because of the very basic functions you have added.
>       For now I am happy to merge if you don't have time now to expand your tests. But ideally, (almost) every line of code you add should be tested (and for a robust package, we should aim at having >90% coverage).
>       You can check what lines/functions lack a test by clicking on the `coverage/coveralls` detail and seeing which lines of code are in red.
I added checks for the availability of `non_uniform_axes` in the tests. Maybe that is the reason for the coverall failure. I will test if the tests run without this check and if they do, aim at getting the coverage increased as much as possible.

**Comment by jlaehne** [comment]
How do I run `coveralls`? it was not automatically launched on the newest PRs.

**Comment by jordiferrero** [comment]
In theory it always runs automatically... It ran in your last commit. Sometimes if you push your commits before all the tests are finished, it does not run coveralls...

Maybe try again with your previous commit and see.

**Comment by jlaehne** [comment]
OK, coveralls just runs with a delay, but it runs in the end. 

However, I did not so far find out why https://github.com/LumiSpy/lumispy/pull/43/commits/d866f46dfa4b795cc70a929e597a592b57ba5b2d had working coverage and now it claims that the coverage has decreased. I have tests included for all of the mentioned lines, and I tried to revert to https://github.com/LumiSpy/lumispy/pull/43/commits/d866f46dfa4b795cc70a929e597a592b57ba5b2d and redo the changes done since then ... maybe related to merging in 'upstream/master', but I don't see why for the moment.

**Comment by jordiferrero** [comment]
Thanks for having a look.
What coveralls is picking as not-covered code is seen here: [here](https://coveralls.io/builds/35200574/source?filename=lumispy%2Fsignals%2Fluminescence_spectrum.py)

It is weird because the `background_subtraction` function has been duplicated when merging with upstream/master... That's OK though.
I'd suggest we merge this PR and then I can have a look in the weekend and try to clear it up (as I have moved and changed completely the `background_subtraction` function).

If you agree, I will merge this PR and close it.

**Comment by jlaehne** [comment]
Added support for relative wavenumber axis.

**Comment by jlaehne** [comment]
Still no idea about the coveralls, now coverage even decreases for files not touched in this PR!

I had the test for availability of the non-uniform axis under suspicion, because it is not really tested - I wouldn't really know how to test that though. But even if I comment out those lines for one of the functions I do not see a better coverage.

**Comment by jordiferrero** [comment]
That is indeed strange. Maybe @ericpre has some idea why the coveralls is failing? He has a better knowledge on CI tools.

**Comment by jlaehne** [comment]
He just changed the tests and fixed the coverage for hyperspy in https://github.com/hyperspy/hyperspy/pull/2592 so maybe that is a starting point to get it to work again here as well.

**Comment by ericpre** [comment]
The coverage is measured from the build on travis but the last commit doesn't have travis build?! Travis seems to reducing capacity massively with build queue going up to 10000, and having to wait for many hours for a single short build to complete.

**Comment by jlaehne** [comment]
Thanks @ericpre.
@jordiferrero, the lines not covered in https://coveralls.io/builds/35394013 concerning axis conversion and joining spectra should be fixed in this PR and #46. Once #47 is merged and the workflow set up, I can merge master into these two branches to run the new tests and coverage.

**Comment by jordiferrero** [comment]
@jlaehne the PR #47 has been now merged so feel free to update this PR and hopefully the coveralls pass now.
Once that is the case, we can merge it to the master branch! Same goes for #46

**Comment by jlaehne** [comment]
Skipping certain tests if non-uniform axes not available, as discussed in #47.

Coverage works like a charm, so now everything should be covered.

**Comment by jordiferrero** [comment]
Hi,
Just quickly resolve the conflicting files and let's merge finally everything :-)

**Comment by jlaehne** [comment]
done ;-)

**Comment by jordiferrero** [comment]
Tedious but all your PRs are now integrated! I think we both learnt something new about the `coveralls` and testing in GitHub :-)

**Comment by jlaehne** [comment]
At least we're much better positioned concerning the testing now. I wanted to update the projects page, but it seems only you have access, @jordiferrero?

**Comment by jordiferrero** [comment]
I've invited to be a member within the LumiSpy repository group. Hopefully this allows you to edit the projects. Let me know @jlaehne

**Comment by jlaehne** [comment]
> I've invited to be a member within the LumiSpy repository group. Hopefully this allows you to edit the projects. Let me know @jlaehne

I think you still have to edit the permissions for the project board: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/project-board-permissions-for-an-organization

**Comment by jordiferrero** [comment]
> > I've invited to be a member within the LumiSpy repository group. Hopefully this allows you to edit the projects. Let me know @jlaehne
> 
> I think you still have to edit the permissions for the project board: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/project-board-permissions-for-an-organization

This should be done now and working.

**Pull request merged**
